spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/donetop
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect

application:
  properties:
    storage:
      root: /home/donetop/storage