server:
  port: 8080
  servlet:
    session:
      timeout: 1440m
      cookie:
        name: DONETOP_MAIN_JSESSIONID
        http-only: true

spring:
  profiles:
    default: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
  datasource:
    url: jdbc:mariadb://localhost:3306/donetop
    username: root
    password: system
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: false
        show_sql: false

application:
  properties:
    base-uri: "http://localhost"
    custom-max-inactive-interval: 31536000 # 1년
    storage:
      root: C:/donetop/storage
    cookieName: DONETOP_MAIN_JSESSIONID

nhn:
  site-cd: T0000
  payment-url: https://stg-spl.kcp.co.kr/gw/enc/v1/payment
  trade-register-url: https://stg-spl.kcp.co.kr/std/tradeReg/register
  cancel-url: https://stg-spl.kcp.co.kr/gw/mod/v1/cancel
  cert-path: nhn/splCert.pem
  private-key-path: nhn/splPrikeyPKCS8.pem
  private-key-password: changeit

logging:
  level:
    com.donetop.main.api.form: DEBUG
    org.springframework.security.web.session: DEBUG