name: CI-CD

on:
  push:
    branches:
    - development
  pull_request:
    branches: 
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
      with:
        submodules: true
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
        gradle-version: 6.9.3
        
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    
    - name: Run build with Gradle Wrapper
      run: ./gradlew donetop-oss:bootJar -Pprofile=aws

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    # - name: Publish to GitHub Packages
    #  uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
    #  with:
    #    arguments: publish
    #  env:
    #    USERNAME: ${{ github.actor }}
    #    TOKEN: ${{ secrets.GITHUB_TOKEN }}
