name: CI-CD

on:
  push:
    branches:
    - development
  pull_request:
    branches: 
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: test

    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.SUBMODULE_PERSONAL_ACCESS_TOKEN }}
        submodules: true
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
        gradle-version: 6.9.3
        
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    
    - name: Run build with Gradle Wrapper
      run: ./gradlew donetop-oss:bootJar -Pprofile=aws
      
    - name: Upload build libs
      uses: actions/upload-artifact@v3
      with:
        name: libs
        path: donetop-oss/build/libs/
        
#     - name: Deploy to Server
#       uses: easingthemes/ssh-deploy@main
#       env:
#         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#         REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#         REMOTE_USER: ${{ secrets.REMOTE_USER }}
#         SOURCE: "donetop-oss/build/libs/"
#         TARGET: ${{ secrets.REMOTE_TARGET }}
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Download build libs
        uses: actions/download-artifact@v3
        with:
          name: libs
          path: donetop-oss/build/libs/
      - run: ls -al donetop-oss/build/libs/
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: donetop-oss/build/libs/
          TARGET: ${{ secrets.REMOTE_TARGET }}
